services:
  postgres:
    image: postgres:17.6-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  adminer:
    image: adminer
    ports:
      - '8080:8080'
    depends_on:
      - postgres

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '8888:80'
    profiles:
      - pgadmin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres

  dbeaver:
    image: dbeaver/cloudbeaver:latest
    ports:
      - '8978:8978'
    profiles:
      - dbeaver
    depends_on:
      - postgres

volumes:
  postgres_data:
  pgadmin-data: